config/routes.rb
ContactOTron::Application.routes.draw do
  resources :contacts

  root :to => redirect('/contacts')
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  include Rails.application.routes.url_helpers

  has_many :phone_numbers, :inverse_of => :contact

  validates :name, :presence => true, :uniqueness => true

  accepts_nested_attributes_for :phone_numbers, :allow_destroy => true, :reject_if => :all_blank

  scope :in_alphabetical_order, order(arel_table[:name].asc)

  def uri
    contact_url self, :host => URI.parse(Plek.current.find('contactotron')).host
  end

  # Customise the payload lazily, so that the environment (e.g. Cucumber) gets
  # the opportunity to configure the transport before the client is created.
  def self.marples_client
    return @marples_client unless @marples_client.nil?

    @marples_client = super.tap do |client|
      client.payload_for self do |contact|
        contact.to_xml :except => contact.attribute_names, :methods => :uri
      end
    end
  end
end

app/models/phone_number.rb
class PhoneNumber < ActiveRecord::Base
  KINDS = %w(phone fax minicom)

  belongs_to :contact

  validates :contact, :kind, :value, :presence => true
  validates :kind, :inclusion => { :in => KINDS }
end

app/models/user.rb
class User < ActiveRecord::Base
  include GDS::SSO::User

  attr_accessible :uid, :email, :name, :permissions, as: :oauth

  serialize :permissions, Hash
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include GDS::SSO::ControllerMethods

  before_filter :set_slimmer_header

  def set_slimmer_header
    headers['X-Slimmer-Template'] = 'admin'
  end
end

app/controllers/contacts_controller.rb
class ContactsController < InheritedResources::Base
  respond_to :html
  respond_to :json, :only => :show
  actions :index, :show, :new, :edit, :create, :update

  before_filter :authenticate_user!, :unless => lambda { |c|
    c.action_name == 'show' && c.request.format.json?
  }

  def show
    show! do |format|
      format.json { render :json => @contact.as_json(:include => :phone_numbers) }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_form.html.erb
<%= form.inputs do %>
  <%= form.input :name %>
  <%= form.input :postal_address %>

  <%= form.inputs 'Phone numbers' do %>
    <% form.object.phone_numbers.each do |phone_number| %>
      <%= semantic_fields_for 'contact[phone_numbers_attributes][]', phone_number, :index => nil do |form| %>
        <li class="phone-group">
          <ul>
          <%= render 'phone_numbers/form', :form => form %>
          <% unless form.object.new_record? %>
            <li class="boolean input optional destroy">
              <label><input name="contact[phone_numbers_attributes][][_destroy]" type="checkbox" value="1"> Delete</label>
            </li>
          <% end %>
          </ul>
        </li>
      <% end %>
    <% end %>

    <%= semantic_fields_for 'contact[phone_numbers_attributes][]', PhoneNumber.new, :index => nil do |form| %>
      <li class="phone-group blank">
        <ul>
          <%= render 'phone_numbers/form', :form => form %>
        </ul>
      </li>
    <% end %>
  <% end %>

  <%= form.input :email_address %>
  <%= form.input :website_url %>
  <%= form.input :opening_hours %>

  <div class="format-controls">
    <li><%= link_to 'Cancel', form.object.new_record? ? contacts_path : contact_path(form.object), :class => 'button' %></li>
    <li><%= form.submit "#{form.object.new_record? ? 'Create' : 'Update'} Contact", :class => form.object.new_record? ? 'create' : 'update' %></li>
  </div>
<% end %>

<%= javascript_tag do %>
  $(function () {
    var blankPhoneNumber = $('.phone-group.blank');
    var button = $('<a>', {
      text:   'Add new phone number',
      class:  'button',
      click:  function () {
        blankPhoneNumber.clone().removeClass('blank').insertBefore(button.closest('li')).slideDown();
      }
    });

    blankPhoneNumber.hide();
    button.insertBefore(blankPhoneNumber).wrap($('<li>').addClass('add-item'));

    $('.phone-group .destroy').each(function () {
      var checkbox = $(this).find('input:checkbox');
      var button = $('<a>', {
        text:   'Delete',
        class:  'button delete-item',
        click:  function () {
          checkbox.prop('checked', !checkbox.prop('checked')).change();
        }
      });

      checkbox.change(function () {
        var deleted = checkbox.prop('checked');

        checkbox.closest('.phone-group')
          [deleted ? 'addClass' : 'removeClass']('deleted', 'normal')
          .find('.button.delete-item')
          .text(deleted ? 'Undo' : 'Delete');
      });

      $(this).hide();
      button.insertAfter(this);
    });
  });
<% end %>

app/views/contacts/edit.html.erb
<h2>Editing contact “<%= @contact.name %>”</h2>

<div class="admin-section">
  <%= semantic_form_for @contact do |form| %>
    <%= render form %>
  <% end %>
</div>

app/views/contacts/index.html.erb
<h2>All contacts</h2>

<div class="admin-section">
  <ul class="contacts">
    <% for contact in @contacts.in_alphabetical_order %>
      <li><%= link_to contact.name, contact_path(contact) %></li>
    <% end %>
  </ul>
</div>

<div class="format-controls">
  <ul>
    <li><%= link_to 'Create new contact', new_contact_path, :class => 'button' %></li>
  </ul>
</div>

app/views/contacts/new.html.erb
<h2>Create new contact</h2>

<div class="admin-section">
  <%= semantic_form_for @contact do |form| %>
    <%= render form %>
  <% end %>
</div>

app/views/contacts/show.html.erb
<h2>Viewing contact "<%= @contact.name %>"</h2>

<div class="admin-section">
  <div class="contact-card">
    <dl>

      <dt>Name:</dt>
      <dd><%= @contact.name %></dd>

      <dt>Postal address:</dt>
      <dd><%= @contact.postal_address %></dd>

      <%= render @contact.phone_numbers %>

      <dt>Email address:</dt>
      <dd><%= @contact.email_address %></dd>
  
      <dt>Website URL:</dt>
      <dd><%= @contact.website_url %></dd>

      <dt>Opening hours:</dt>
      <dd><%= @contact.opening_hours %></dd>
    
    </dl>
  </div>
</div>

<div class="format-controls">
  
  <ul>
    <li>
      <%= link_to 'Edit contact', edit_contact_path, :class => 'button' %>
    </li>
  </ul>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Contact-o-tron</title>
  <%= stylesheet_link_tag '/stylesheets/formtastic.css', '/stylesheets/formtastic_changes.css' %>
  <%= stylesheet_link_tag "/contacts-assets/stylesheets/contacts" %>
  <%= javascript_include_tag "application" %>
  <meta name="x-section-name" content="Contact-o-tron" />
  <meta name="x-section-link" content="contact-o-tron" />
  <%= csrf_meta_tags %>
</head>
<body>

  <h1 id="site-title">Contact-o-tron</h1>

  <div id="wrapper" class="wrapper">

    <nav class="admin-nav group" role="navigation">
    	<ul>
        <li><%= link_to 'All contacts', contacts_path %></li>
        <li><%= link_to 'Sign out', gds_sign_out_path %></li>
    	</ul>
    </nav>

    <div class="content" role="main">
      <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/phone_numbers/_form.html.erb
<%= form.input :kind, :collection => PhoneNumber::KINDS %>
<%= form.input :label %>
<%= form.input :value, :label => 'Number' %>
<%= form.input :id, :as => :hidden %>

app/views/phone_numbers/_phone_number.html.erb
<dt><%= phone_number.kind.humanize %> number<%= " (#{phone_number.label})" if phone_number.label.present? %>:</dt>
<dd><%= phone_number.value %></dd>